server:
  port: 88
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 前端项目 /api
    gateway:
      routes:
        - id: admin_route
          uri: lb://blog-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /blog-admin/$\{segment}