server:
  port: 88
spring:
  application:
    name: blog-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 前端项目 /dev-api
    gateway:
      routes:
        - id: third_party_route
          uri: lb://blog-third-party
          predicates:
            - Path=/dev-api/thirdparty/**
          filters:
            - RewritePath=/dev-api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://blog-admin
          predicates:
            - Path=/dev-api/**
          filters:
            - RewritePath=/dev-api/(?<segment>/?.*), /blog-admin/$\{segment}